apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cliptown
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cliptown/cliptown-infra.git
    targetRevision: main
    path: .
    helm:
      releaseName: cliptown-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
