apiVersion: v1
kind: ConfigMap
metadata:
  name: cliptown-api-runtime
  namespace: cliptown-canary
data:
  shared-auth-base-url: https://auth.oresoftware.dev
  shared-auth-issuer: https://auth.oresoftware.dev
