name: Lint Infra

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Lint Helm Chart
        run: helm lint .
